######  说明  ######
# 1、Fork 本仓库
# 2、在你 Fork 的本仓库下的 Settings > Secrets 画面追加以下几个 secret 变量：
# FREENOM_USERNAME、FREENOM_PASSWORD、MULTIPLE_ACCOUNTS、MAIL_USERNAME、MAIL_PASSWORD、TO、MAIL_ENABLE、TELEGRAM_CHAT_ID、
# TELEGRAM_BOT_TOKEN、TELEGRAM_BOT_ENABLE、NOTICE_FREQ
# （注：此处列出了所有可用变量，你只用追加你需要用到的变量，变量的具体含义请参考本项目的 .env 文件中的说明，一般情况下，.env 文件中的某些
#  项存在默认值，如果默认值满足你的需求则可不追加到 Secrets，它们会保持默认）
#
# 下面定时任务中的时间是世界时间，每天 10:00 执行，由于创建虚拟环境会消耗时间，故任务会延迟 30 秒左右执行
#
# @Author of yml configuration file: RouRouX <https://github.com/RouRouX> & mybsdc <mybsdc@gmail.com>
#
######  end 说明  ######

name: Run it on action

on:
  push:
    branches:
      - master
  schedule:
    - cron: 00 02 * * *

#env:
#  CONFIG_FILE: .env.example

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Run it on action
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
      
      - name: Clone source code
        run:  git clone https://github.com/luolongfei/freenom.git
 
      - name: copy env
        run:  cd freenom && cp .env.example .env
      
#      - name: mv env
#        run: [ -e $CONFIG_FILE ] && mv $CONFIG_FILE freenom/.env
      
      - name: Run
        run: |
          cd freenom
          php run
